services:
  # web:
  #   build: .
  #   command: npm start
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./web
  #         target: /src/web
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: package.json
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./backend:/app  # Syncs local backend code with the container
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev  # Enables live-reloading (uses nodemon)

  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app  # Syncs local frontend code with the container
      - /app/node_modules  # Prevents overwriting node_modules
    command: npm run dev  # Enables Next.js hot reloading

networks:
  app-network:
    driver: bridge