services:
  backend:
    build: ./backend
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend  # ✅ Only frontend should depend on backend
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/.next:/app/.next  # Persist Next.js cache

networks:
  app-network:
    driver: bridge